name: docker build
 
on:
  push:
    branches: [ master ]

 
jobs:
  build:
 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: installnpm
      run: npm install
    - name: build image
      run:  docker build . --file Dockerfile --tag registry.cn-qingdao.aliyuncs.com/delong1998/cors:dev
    - name: push docker image
      run: docker push registry.cn-qingdao.aliyuncs.com/delong1998/cors:dev
    - name: docker logout
      run: docker logout registry.cn-qingdao.aliyuncs.com
           
